version: '3'

services:
  app:
    build:
      context: ./dockerfile/php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8080" ]

  composer:
    image: composer
    volumes:
      - .:/app
    command: [ "composer", "install" ]
